export default {
  id: 1,
  title: 'Ordering Food',
  location: 'Mexico City',
  steps: [
    { type: 'teach', phrase: 'Me regala unos tacos, por favor',
      translation: 'Could you give me some tacos, please',
      culture: 'In Mexico, "me regala" (literally "gift me") is the warm, polite way to order. "Quiero" (I want) sounds demanding — locals rarely use it with waiters.' },
    { type: 'teach', phrase: '¿Qué me recomienda?',
      translation: 'What do you recommend?',
      culture: 'Asking for a recommendation is a sign of respect and often gets you the best dish in the house.' },
    { type: 'quiz', question: 'You want to order tacos politely. What do you say?',
      options: ['Quiero tacos', 'Me regala unos tacos, por favor', 'Dame tacos ahora'],
      correctIndex: 1,
      feedbackCorrect: '¡Exacto! "Me regala" is warm and polite — this is how locals order.',
      feedbackWrong: 'Not quite — "quiero" or "dame" sound demanding in Mexico. "Me regala" is the friendly way.' },
    { type: 'quiz', question: 'The waiter brings your food. A natural response?',
      options: ['Gracias, se ve muy rico', 'OK', 'Está bien'],
      correctIndex: 0,
      feedbackCorrect: '¡Perfecto! Complimenting the food ("it looks delicious") is warm and very Mexican.',
      feedbackWrong: 'Locals usually add warmth — "Gracias, se ve muy rico" compliments the food and builds rapport.' },
  ],
};
