-- v3 Phase 2: AI-generated learning plans.
--
-- One plan per user per language, generated by the generate-learning-plan
-- edge function from the onboarding fields (level_estimate, goal, goal_date,
-- daily_minutes) and replaced on regeneration. source_snapshot captures the
-- onboarding fields at generation time so the app can detect when they've
-- drifted and offer a refresh (lib/learningPlan.shouldOfferRegeneration).
--
-- plan_json schema (produced via Gemini structured output, validated in the
-- function before insert):
-- {
--   "summary": "string — one friendly sentence about the plan",
--   "estimated_weeks": number,
--   "weekly_minutes_target": number,
--   "milestones": [
--     { "week": number, "title": "string", "focus": "string",
--       "recommended_lessons": ["lesson_id", ...] }
--   ],
--   "notes": "string — optional coaching note about pace/goal"
-- }
--
-- recommended_lessons only ever contains real lesson_ids — the function
-- filters Gemini's output against the app's lesson registry post-generation.

create table if not exists public.learning_plans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  language text not null,
  plan_json jsonb not null,
  generated_at timestamptz not null default now(),
  source_snapshot jsonb not null,
  unique (user_id, language)
);

alter table public.learning_plans enable row level security;

-- Own-row only, all four verbs. The edge function upserts with the caller's
-- own JWT (user-scoped client), so these policies bind it too — no
-- service-role path is needed for this feature.
drop policy if exists "own plan select" on public.learning_plans;
create policy "own plan select" on public.learning_plans
for select using (user_id = auth.uid());

drop policy if exists "own plan insert" on public.learning_plans;
create policy "own plan insert" on public.learning_plans
for insert with check (user_id = auth.uid());

drop policy if exists "own plan update" on public.learning_plans;
create policy "own plan update" on public.learning_plans
for update using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "own plan delete" on public.learning_plans;
create policy "own plan delete" on public.learning_plans
for delete using (user_id = auth.uid());
