export default {
  id: 'es-MX/market-1',
  lessonType: 'scenario',
  title: 'At the Market',
  location: 'Oaxaca',
  steps: [
    { id: 'market-1-s01', type: 'word', phrase: 'el kilo', translation: 'the kilo', note: 'Markets sell by weight: kilo, medio kilo (half), un cuarto (quarter).' },
    { id: 'market-1-s02', type: 'word', phrase: 'el mango', translation: 'the mango' },
    { id: 'market-1-s03', type: 'word', phrase: 'a cómo', translation: 'how much (market style)', note: 'The authentic market way to ask price — instantly less touristy than "cuánto cuesta".' },
    { id: 'market-1-s04', type: 'teach', phrase: '¿A cómo el kilo de mango?',
      translation: 'How much is a kilo of mango?',
      culture: 'In markets, locals say "¿a cómo...?" instead of "¿cuánto cuesta?" — vendors will treat you like a local.' },
    { id: 'market-1-s05', type: 'quiz', question: 'The market way to ask a price is...',
      options: ['¿A cómo...?', '¿Dónde está...?', '¿Qué es...?'],
      correctIndex: 0,
      feedbackCorrect: '¡Órale! "¿A cómo...?" — you sound like a regular already.',
      feedbackWrong: '"¿A cómo...?" is the market phrase. ("Dónde" = where, "qué" = what.)' },
    { id: 'market-1-s06', type: 'word', phrase: 'dejar', translation: 'to leave / to let have', note: 'In haggling: "¿me lo deja en...?" = "would you let me have it for...?"' },
    { id: 'market-1-s07', type: 'word', phrase: 'veinte', translation: 'twenty' },
    { id: 'market-1-s08', type: 'teach', phrase: '¿Me lo deja en veinte?',
      translation: 'Would you let me have it for twenty?',
      culture: 'Gentle haggling is normal and expected at markets (never in supermarkets). Keep it friendly and smiling — it\'s a social ritual, not a battle.' },
    { id: 'market-1-s09', type: 'word', phrase: 'medio kilo', translation: 'half a kilo' },
    { id: 'market-1-s10', type: 'teach', phrase: 'Deme medio kilo, por favor',
      translation: 'Give me half a kilo, please',
      culture: 'At market stalls "deme" (give me) is normal and friendly when buying by weight — softer rules than restaurants.' },
    { id: 'market-1-s11', type: 'quiz', question: 'You want to ask the price of avocados the local way:',
      options: ['¿Cuánto cuesta el aguacate?', '¿A cómo el aguacate?', 'Precio, por favor'],
      correctIndex: 1,
      feedbackCorrect: '¡Órale! "¿A cómo...?" — the true market phrase.',
      feedbackWrong: '"¿Cuánto cuesta?" works, but "¿a cómo...?" is what locals say at markets.' },
    { id: 'market-1-s12', type: 'quiz', question: 'Vendor says 30 pesos, you think it\'s high. What\'s appropriate?',
      options: ['Walk away silently', 'Smile and ask "¿Me lo deja en veinte?"', 'Say "¡Es demasiado caro!" loudly'],
      correctIndex: 1,
      feedbackCorrect: '¡Perfecto! "Dejar" + a smile = friendly haggling, market style.',
      feedbackWrong: 'Haggling is welcome but friendly — remember "dejar": "¿Me lo deja en veinte?"' },
  ],
};
