export default {
  id: 2,
  title: 'Getting Around',
  location: 'Mexico City',
  steps: [
    { type: 'word', phrase: 'llevar', translation: 'to take / carry', note: 'Taxi essential: "¿me lleva...?" = "can you take me...?"' },
    { type: 'word', phrase: 'cobrar', translation: 'to charge (money)' },
    { type: 'word', phrase: 'la esquina', translation: 'the corner' },
    { type: 'word', phrase: 'cuánto', translation: 'how much' },
    { type: 'teach', phrase: '¿Me lleva al Zócalo, por favor?',
      translation: 'Can you take me to the Zócalo, please?',
      culture: 'With taxi drivers, phrasing requests as questions ("¿me lleva...?") is the polite norm. Stating destinations flatly can come across as cold.' },
    { type: 'quiz', question: '"Cobrar" means...',
      options: ['to drive', 'to charge money', 'to stop'],
      correctIndex: 1,
      feedbackCorrect: '¡Bien! "Cobrar" = to charge. You\'ll need it for the next phrase.',
      feedbackWrong: '"Cobrar" means to charge money — key word for negotiating taxi fares.' },
    { type: 'teach', phrase: '¿Cuánto me cobra?',
      translation: 'How much will you charge me?',
      culture: 'For street taxis without meters, ALWAYS agree on the price before getting in. Asking "¿cuánto me cobra?" upfront is expected, not rude.' },
    { type: 'teach', phrase: 'Me deja en la esquina, por favor',
      translation: 'Drop me off at the corner, please',
      culture: 'Mexicans often give drop-off points by landmarks and corners ("la esquina", "la farmacia") rather than exact addresses — it\'s how locals navigate.' },
    { type: 'quiz', question: 'You\'re getting into a street taxi with no meter. What do you do first?',
      options: ['Get in and hope for the best', 'Ask "¿Cuánto me cobra?" before getting in', 'Show them cash'],
      correctIndex: 1,
      feedbackCorrect: '¡Exacto! "Cuánto" (how much) + "cobrar" (to charge) — agree on the price first.',
      feedbackWrong: 'Always agree on the price BEFORE the ride — "¿Cuánto me cobra?" is the expected question.' },
    { type: 'quiz', question: 'How do you politely ask a driver to take you downtown?',
      options: ['Lléveme al centro', '¿Me lleva al centro, por favor?', 'Al centro. Ahora.'],
      correctIndex: 1,
      feedbackCorrect: '¡Muy bien! "Llevar" in question form + "por favor" — exactly how locals ask.',
      feedbackWrong: 'Commands sound harsh. Use "llevar" as a question: "¿Me lleva al centro, por favor?"' },
  ],
};
