export default {
  id: 'es-MX/letters-1',
  lessonType: 'letters',
  title: 'Sounds of Spanish',
  location: 'México',
  steps: [
    { type: 'teach', glyph: 'a', name: 'a', example: 'gracias', exampleTranslation: 'thank you' },
    { type: 'teach', glyph: 'e', name: 'e', example: 'el', exampleTranslation: 'the' },
    { type: 'teach', glyph: 'i', name: 'i', example: 'kilo', exampleTranslation: 'kilo' },
    { type: 'teach', glyph: 'o', name: 'o', example: 'cómo', exampleTranslation: 'how' },
    { type: 'teach', glyph: 'u', name: 'u', example: 'cuánto', exampleTranslation: 'how much' },
    { type: 'teach', glyph: 'ñ', name: 'eñe', example: 'año', exampleTranslation: 'year' },
    { type: 'teach', glyph: 'll', name: 'elle', example: 'llevar', exampleTranslation: 'to take / carry' },
    { type: 'teach', glyph: 'rr', name: 'erre', example: 'arroz', exampleTranslation: 'rice' },
    { type: 'teach', glyph: 'j', name: 'jota', example: 'jitomate', exampleTranslation: 'tomato' },
    { type: 'teach', glyph: 'h', name: 'hache', example: 'hola', exampleTranslation: 'hello',
      note: 'The h is always silent in Spanish — "hola" sounds like "ola".' },
    { type: 'teach', glyph: 'qu', name: 'cu', example: 'qué', exampleTranslation: 'what',
      note: '"qu" always makes a hard "k" sound — never "kw".' },

    { type: 'quiz', audioText: 'eñe', question: 'Which letter did you hear?',
      options: ['ñ', 'n', 'm', 'll'], correctIndex: 0,
      feedbackCorrect: '¡Exacto! "Eñe" — the tilde changes the sound completely.',
      feedbackWrong: 'That was "eñe" — the ñ with a tilde on top, as in "año".' },
    { type: 'quiz', audioText: 'elle', question: 'Which letter did you hear?',
      options: ['ll', 'l', 'y', 'rr'], correctIndex: 0,
      feedbackCorrect: '¡Bien! "Elle" — double-l, as in "llevar".',
      feedbackWrong: 'That was "elle" — double-l, as in "llevar".' },
    { type: 'quiz', audioText: 'erre', question: 'Which letter did you hear?',
      options: ['rr', 'r', 'l', 'j'], correctIndex: 0,
      feedbackCorrect: '¡Perfecto! "Erre" — the strong rolled r, as in "arroz".',
      feedbackWrong: 'That was "erre" — the strong rolled r, as in "arroz".' },
    { type: 'quiz', audioText: 'jota', question: 'Which letter did you hear?',
      options: ['j', 'h', 'g', 'x'], correctIndex: 0,
      feedbackCorrect: '¡Correcto! "Jota" makes a strong "h" sound, as in "jitomate".',
      feedbackWrong: 'That was "jota" — it makes a strong "h" sound, as in "jitomate".' },
    { type: 'quiz', audioText: 'cu', question: 'Which letters did you hear?',
      options: ['qu', 'c', 'k', 'g'], correctIndex: 0,
      feedbackCorrect: '¡Exacto! "Cu" — always a hard "k" sound, as in "qué".',
      feedbackWrong: 'That was "cu" — "qu" always makes a hard "k" sound, as in "qué".' },
  ],
};
