export default {
  id: 'es-MX/numbers-1',
  lessonType: 'numbers',
  title: 'Numbers & Prices',
  location: 'Oaxaca',
  steps: [
    { type: 'teach', number: 1, word: 'uno', phrase: 'Es un peso.', phraseTranslation: "It's one peso." },
    { type: 'teach', number: 2, word: 'dos', phrase: 'Son dos pesos.', phraseTranslation: "That's two pesos." },
    { type: 'teach', number: 3, word: 'tres', phrase: 'Son tres pesos.', phraseTranslation: "That's three pesos." },
    { type: 'teach', number: 4, word: 'cuatro', phrase: 'Son cuatro pesos.', phraseTranslation: "That's four pesos." },
    { type: 'teach', number: 5, word: 'cinco', phrase: 'Son cinco pesos.', phraseTranslation: "That's five pesos." },
    { type: 'listen-pick', audioText: 'tres', correctNumber: 3, options: [3, 8, 13, 30] },

    { type: 'teach', number: 6, word: 'seis', phrase: 'Cuestan seis pesos.', phraseTranslation: 'They cost six pesos.' },
    { type: 'teach', number: 7, word: 'siete', phrase: 'Son siete pesos.', phraseTranslation: "That's seven pesos." },
    { type: 'teach', number: 8, word: 'ocho', phrase: 'Son ocho pesos.', phraseTranslation: "That's eight pesos." },
    { type: 'teach', number: 9, word: 'nueve', phrase: 'Cuestan nueve pesos.', phraseTranslation: 'They cost nine pesos.' },
    { type: 'teach', number: 10, word: 'diez', phrase: 'Son diez pesos.', phraseTranslation: "That's ten pesos.",
      culture: 'Prices in Mexico are almost always in pesos (MXN), not dollars — even in tourist areas. If a price ever sounds surprisingly low, confirm "¿Pesos?" before celebrating.' },
    { type: 'listen-pick', audioText: 'nueve', correctNumber: 9, options: [9, 19, 90, 6] },

    { type: 'teach', number: 11, word: 'once', phrase: 'Son once pesos.', phraseTranslation: "That's eleven pesos." },
    { type: 'teach', number: 12, word: 'doce', phrase: 'Cuestan doce pesos.', phraseTranslation: 'They cost twelve pesos.' },
    { type: 'teach', number: 13, word: 'trece', phrase: 'Son trece pesos.', phraseTranslation: "That's thirteen pesos." },
    { type: 'teach', number: 14, word: 'catorce', phrase: 'Son catorce pesos.', phraseTranslation: "That's fourteen pesos." },
    { type: 'teach', number: 15, word: 'quince', phrase: 'Son quince pesos, por favor.', phraseTranslation: "That's fifteen pesos, please.",
      culture: 'To ask a price, say "¿Cuánto cuesta?" (how much does it cost) — or at a market stall, "¿A cómo lo da?" (what price are you giving it for). Both are natural and polite.' },
    { type: 'listen-pick', audioText: 'catorce', correctNumber: 14, options: [14, 4, 40, 15] },

    { type: 'teach', number: 20, word: 'veinte', phrase: '¿Me lo deja en veinte?', phraseTranslation: 'Would you let me have it for twenty?',
      culture: 'Gentle haggling is normal and expected at street markets (tianguis) — but not in supermarkets or fixed-price stores.' },
    { type: 'teach', number: 50, word: 'cincuenta', phrase: 'Son cincuenta pesos.', phraseTranslation: "That's fifty pesos." },
    { type: 'teach', number: 100, word: 'cien', phrase: 'Son cien pesos en total.', phraseTranslation: "That's a hundred pesos total." },
    { type: 'listen-pick', audioText: 'cincuenta', correctNumber: 50, options: [50, 15, 5, 100] },

    { type: 'quiz', quizVariant: 'seeNumeralPickWord', number: 12,
      options: ['doce', 'dos', 'trece', 'veinte'], correctIndex: 0,
      feedbackCorrect: '¡Exacto! 12 es "doce".',
      feedbackWrong: '12 se dice "doce".' },
    { type: 'quiz', quizVariant: 'hearWordPickNumeral', word: 'cien',
      options: [100, 10, 1, 50], correctIndex: 0,
      feedbackCorrect: '¡Perfecto! "Cien" es 100.',
      feedbackWrong: '"Cien" es 100 — no lo confundas con "diez" (10).' },
    { type: 'quiz', quizVariant: 'seeNumeralPickWord', number: 20,
      options: ['veinte', 'diez', 'doce', 'trece'], correctIndex: 0,
      feedbackCorrect: '¡Muy bien! 20 es "veinte".',
      feedbackWrong: '20 se dice "veinte".' },
    { type: 'quiz', quizVariant: 'hearWordPickNumeral', word: 'quince',
      options: [15, 50, 5, 14], correctIndex: 0,
      feedbackCorrect: '¡Correcto! "Quince" es 15.',
      feedbackWrong: '"Quince" es 15 — cuidado con "cinco" (5).' },
  ],
};
