export default {
  id: 'es-MX/food-1',
  lessonType: 'scenario',
  title: 'Ordering Food',
  location: 'Mexico City',
  steps: [
    { type: 'word', phrase: 'los tacos', translation: 'tacos', note: 'Your most important word in Mexico 🌮' },
    { type: 'word', phrase: 'por favor', translation: 'please' },
    { type: 'word', phrase: 'me regala', translation: 'could you give me (lit. "gift me")', note: 'THE polite Mexican way to ask for things.' },
    { type: 'teach', phrase: 'Me regala unos tacos, por favor',
      translation: 'Could you give me some tacos, please',
      culture: 'In Mexico, "me regala" is the warm, polite way to order. "Quiero" (I want) sounds demanding — locals rarely use it with waiters.' },
    { type: 'quiz', question: 'What does "me regala" literally mean?',
      options: ['I want', 'Gift me', 'Bring me'],
      correctIndex: 1,
      feedbackCorrect: '¡Exacto! It literally means "gift me" — that\'s what makes it so warm and polite.',
      feedbackWrong: 'It literally means "gift me" — a warm way of asking that\'s uniquely Mexican.' },
    { type: 'word', phrase: 'recomendar', translation: 'to recommend' },
    { type: 'word', phrase: 'qué', translation: 'what' },
    { type: 'teach', phrase: '¿Qué me recomienda?',
      translation: 'What do you recommend?',
      culture: 'Asking for a recommendation is a sign of respect and often gets you the best dish in the house.' },
    { type: 'word', phrase: 'rico', translation: 'delicious / tasty', note: 'Mexicans say "rico" constantly about food — more common than "delicioso".' },
    { type: 'teach', phrase: 'Gracias, se ve muy rico',
      translation: 'Thank you, it looks delicious',
      culture: 'Complimenting the food when it arrives is warm and very Mexican — it builds rapport with staff.' },
    { type: 'quiz', question: 'You want to order tacos politely. What do you say?',
      options: ['Quiero tacos', 'Me regala unos tacos, por favor', 'Dame tacos ahora'],
      correctIndex: 1,
      feedbackCorrect: '¡Exacto! "Me regala" + "por favor" — warm and polite, just like a local.',
      feedbackWrong: 'Not quite — "quiero" or "dame" sound demanding. "Me regala unos tacos, por favor" is the friendly way.' },
    { type: 'quiz', question: 'The food arrives and looks great. A natural response?',
      options: ['Gracias, se ve muy rico', 'OK', 'Está bien'],
      correctIndex: 0,
      feedbackCorrect: '¡Perfecto! You used "rico" like a true Mexican.',
      feedbackWrong: 'Remember "rico" (delicious)? "Gracias, se ve muy rico" compliments the food and builds warmth.' },
  ],
};
