export default {
  id: 'es-MX/food-1',
  lessonType: 'scenario',
  title: 'Ordering Food',
  location: 'Mexico City',
  steps: [
    { id: 'food-1-s01', type: 'word', phrase: 'los tacos', translation: 'tacos', note: 'Your most important word in Mexico 🌮' },
    { id: 'food-1-s02', type: 'word', phrase: 'por favor', translation: 'please' },
    { id: 'food-1-s03', type: 'word', phrase: 'me regala', translation: 'could you give me (lit. "gift me")', note: 'THE polite Mexican way to ask for things.' },
    { id: 'food-1-s04', type: 'teach', phrase: 'Me regala unos tacos, por favor',
      translation: 'Could you give me some tacos, please',
      culture: 'In Mexico, "me regala" is the warm, polite way to order. "Quiero" (I want) sounds demanding — locals rarely use it with waiters.' },
    { id: 'food-1-s05', type: 'quiz', question: 'What does "me regala" literally mean?',
      options: ['I want', 'Gift me', 'Bring me'],
      correctIndex: 1,
      feedbackCorrect: '¡Exacto! It literally means "gift me" — that\'s what makes it so warm and polite.',
      feedbackWrong: 'It literally means "gift me" — a warm way of asking that\'s uniquely Mexican.' },
    { id: 'food-1-s06', type: 'word', phrase: 'recomendar', translation: 'to recommend' },
    { id: 'food-1-s07', type: 'word', phrase: 'qué', translation: 'what' },
    { id: 'food-1-s08', type: 'teach', phrase: '¿Qué me recomienda?',
      translation: 'What do you recommend?',
      culture: 'Asking for a recommendation is a sign of respect and often gets you the best dish in the house.' },
    { id: 'food-1-s09', type: 'word', phrase: 'rico', translation: 'delicious / tasty', note: 'Mexicans say "rico" constantly about food — more common than "delicioso".' },
    { id: 'food-1-s10', type: 'teach', phrase: 'Gracias, se ve muy rico',
      translation: 'Thank you, it looks delicious',
      culture: 'Complimenting the food when it arrives is warm and very Mexican — it builds rapport with staff.' },
    { id: 'food-1-s11', type: 'quiz', question: 'You want to order tacos politely. What do you say?',
      options: ['Quiero tacos', 'Me regala unos tacos, por favor', 'Dame tacos ahora'],
      correctIndex: 1,
      feedbackCorrect: '¡Exacto! "Me regala" + "por favor" — warm and polite, just like a local.',
      feedbackWrong: 'Not quite — "quiero" or "dame" sound demanding. "Me regala unos tacos, por favor" is the friendly way.' },
    { id: 'food-1-s12', type: 'quiz', question: 'The food arrives and looks great. A natural response?',
      options: ['Gracias, se ve muy rico', 'OK', 'Está bien'],
      correctIndex: 0,
      feedbackCorrect: '¡Perfecto! You used "rico" like a true Mexican.',
      feedbackWrong: 'Remember "rico" (delicious)? "Gracias, se ve muy rico" compliments the food and builds warmth.' },

    // --- Phase: new interactive step-type SEEDS (one of each) ---------------
    { id: 'food-1-s13', type: 'listen', phrase: 'los tacos',
      question: 'What did you hear?',
      options: ['tacos', 'please', 'the corner'],
      correctIndex: 0,
      feedbackCorrect: '¡Sí! "los tacos" — tacos.',
      feedbackWrong: 'That was "los tacos" — tacos.' },
    { id: 'food-1-s14', type: 'fill', prompt: 'Fill in the blank',
      frame: 'Me regala ___ tacos, por favor', answer: 'unos',
      feedbackCorrect: '¡Exacto! "unos tacos" — some tacos.',
      feedbackWrong: 'The word is "unos" (some) — note it\'s masculine to match "tacos".' },
    { id: 'food-1-s15', type: 'build', prompt: 'Build the sentence',
      translation: 'Could you give me some tacos, please',
      answer: 'Me regala unos tacos por favor', extraTiles: ['quiero'],
      feedbackCorrect: '¡Bien hecho!',
      feedbackWrong: 'The order is "Me regala unos tacos por favor".' },
    { id: 'food-1-s16', type: 'speak', phrase: 'Gracias, se ve muy rico',
      prompt: 'Say: "Thank you, it looks delicious"',
      feedbackCorrect: '¡Perfecto! That sounded great.',
      feedbackWrong: 'Aim for "Gracias, se ve muy rico".' },
    { id: 'food-1-s17', type: 'match',
      pairs: [
        { es: 'los tacos', en: 'tacos' },
        { es: 'por favor', en: 'please' },
        { es: 'rico', en: 'delicious' },
      ] },
  ],
};
